version: '3'
services:
  jekyll-conradakunga_blog_build:
      build:
          context: .
          dockerfile: Dockerfile
      environment:
          - JEKYLL_ENV=production
      command: jekyll build
      ports:
          - 4000:4000
          - 35729:35729
      volumes:
          - .:/srv/jekyll